import { DDRAGON_VERSION } from '../data/ddragonVersion'
import type { DDragonChampion, DDragonChampionSpell, DDragonItem, DDragonRuneTree, DDragonSummonerSpell } from '../types/ddragon'
import type { ChampionSimData } from '../types/simulator'

const CDN = 'https://ddragon.leagueoflegends.com'

async function cachedFetch<T>(cacheKey: string, url: string): Promise<T> {
  const cached = localStorage.getItem(cacheKey)
  if (cached) {
    try {
      return JSON.parse(cached) as T
    } catch {
      // fall through and refetch
    }
  }
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`)
  const data = (await res.json()) as T
  localStorage.setItem(cacheKey, JSON.stringify(data))
  return data
}

export async function getChampions(): Promise<DDragonChampion[]> {
  const raw = await cachedFetch<{ data: Record<string, DDragonChampion> }>(
    `ddragon:${DDRAGON_VERSION}:champions`,
    `${CDN}/cdn/${DDRAGON_VERSION}/data/en_US/champion.json`,
  )
  return Object.values(raw.data).sort((a, b) => a.name.localeCompare(b.name))
}

// A champion's Q/W/E/R, in that order. Only the trimmed spell list is cached — the full
// per-champion file (lore, skins, tips, ...) would bloat localStorage across many champions.
export async function getChampionSpells(championId: string): Promise<DDragonChampionSpell[]> {
  const cacheKey = `ddragon:${DDRAGON_VERSION}:championSpells:${championId}`
  const cached = localStorage.getItem(cacheKey)
  if (cached) {
    try {
      return JSON.parse(cached) as DDragonChampionSpell[]
    } catch {
      // fall through and refetch
    }
  }
  const url = `${CDN}/cdn/${DDRAGON_VERSION}/data/en_US/champion/${championId}.json`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`)
  const raw = (await res.json()) as { data: Record<string, { spells: DDragonChampionSpell[] }> }
  const spells = (raw.data[championId]?.spells ?? []).map(({ id, name, description, image }) => ({
    id,
    name,
    description,
    image: { full: image.full },
  }))
  localStorage.setItem(cacheKey, JSON.stringify(spells))
  return spells
}

// Pre-generated by scripts/gen-champion-data.mjs and served from public/ — static and HTTP-cached,
// so it isn't mirrored into localStorage like the Data Dragon fetches above.
const simDataCache = new Map<string, Promise<ChampionSimData>>()

export function getChampionSimData(championId: string): Promise<ChampionSimData> {
  let pending = simDataCache.get(championId)
  if (!pending) {
    pending = fetch(`${import.meta.env.BASE_URL}data/champions/${championId}.json`).then((res) => {
      if (!res.ok) throw new Error(`No simulator data for ${championId} (${res.status})`)
      return res.json() as Promise<ChampionSimData>
    })
    pending.catch(() => simDataCache.delete(championId))
    simDataCache.set(championId, pending)
  }
  return pending
}

interface RawDDragonItem extends DDragonItem {
  gold: { total: number; purchasable: boolean }
  maps: Record<string, boolean>
  into: string[]
  requiredChampion?: string
  hideFromAll?: boolean
}

// ARAM-only starter items (Guardian's Horn/Orb/Blade/Hammer, Cappa Juice) are flagged as
// available on map 11 too, even though they can't actually be bought on Summoner's Rift.
const ARAM_STARTER_ITEM_IDS = new Set(['2051', '3112', '3177', '3184', '2141'])

export async function getItems(): Promise<DDragonItem[]> {
  const raw = await cachedFetch<{ data: Record<string, RawDDragonItem> }>(
    `ddragon:${DDRAGON_VERSION}:items`,
    `${CDN}/cdn/${DDRAGON_VERSION}/data/en_US/item.json`,
  )
  // Other game modes (Arena, ...) reuse an existing item's name under their own six-digit
  // id, incorrectly flagged as available on map 11 too; drop those so items aren't listed
  // twice, and so mode-exclusive items whose real SR id was retired don't show up at all.
  const bestByName = new Map<string, [string, RawDDragonItem]>()
  for (const [id, item] of Object.entries(raw.data)) {
    if (!item.gold.purchasable || !item.maps['11'] || Number(id) >= 100000) continue
    if (item.requiredChampion || item.hideFromAll || ARAM_STARTER_ITEM_IDS.has(id)) continue
    const existing = bestByName.get(item.name)
    if (!existing || Number(id) < Number(existing[0])) bestByName.set(item.name, [id, item])
  }
  return Array.from(bestByName.values())
    .map(([id, item]) => ({
      id,
      name: item.name,
      description: item.description,
      image: item.image,
      tags: item.tags,
      gold: { total: item.gold.total },
      into: item.into ?? [],
      stats: item.stats ?? {},
    }))
    .sort((a, b) => a.gold.total - b.gold.total)
}

export async function getRuneTrees(): Promise<DDragonRuneTree[]> {
  return cachedFetch<DDragonRuneTree[]>(
    `ddragon:${DDRAGON_VERSION}:runes`,
    `${CDN}/cdn/${DDRAGON_VERSION}/data/en_US/runesReforged.json`,
  )
}

// Same order as the game's own spell list (Flash, Ignite, Smite, ...). Any spell Riot adds later
// that isn't listed here goes after these, alphabetically.
const SUMMONER_SPELL_ORDER = [
  'SummonerFlash',
  'SummonerDot',
  'SummonerSmite',
  'SummonerTeleport',
  'SummonerBarrier',
  'SummonerHeal',
  'SummonerExhaust',
  'SummonerHaste',
  'SummonerBoost',
]

export async function getSummonerSpells(): Promise<DDragonSummonerSpell[]> {
  const raw = await cachedFetch<{ data: Record<string, DDragonSummonerSpell> }>(
    `ddragon:${DDRAGON_VERSION}:summonerSpells`,
    `${CDN}/cdn/${DDRAGON_VERSION}/data/en_US/summoner.json`,
  )
  const rank = (spell: DDragonSummonerSpell) => {
    const index = SUMMONER_SPELL_ORDER.indexOf(spell.id)
    return index === -1 ? SUMMONER_SPELL_ORDER.length : index
  }
  return Object.values(raw.data)
    .filter((spell) => spell.modes.includes('CLASSIC'))
    .sort((a, b) => rank(a) - rank(b) || a.name.localeCompare(b.name))
}

export function championImageUrl(fullImageName: string): string {
  return `${CDN}/cdn/${DDRAGON_VERSION}/img/champion/${fullImageName}`
}

export function championLoadingUrl(championId: string): string {
  return `${CDN}/cdn/img/champion/loading/${championId}_0.jpg`
}

export function itemImageUrl(fullImageName: string): string {
  return `${CDN}/cdn/${DDRAGON_VERSION}/img/item/${fullImageName}`
}

export function passiveImageUrl(fullImageName: string): string {
  return `${CDN}/cdn/${DDRAGON_VERSION}/img/passive/${fullImageName}`
}

export function runeIconUrl(icon: string): string {
  return `${CDN}/cdn/img/${icon}`
}

// Summoner spells and champion abilities share Data Dragon's img/spell folder.
export function summonerSpellImageUrl(fullImageName: string): string {
  return `${CDN}/cdn/${DDRAGON_VERSION}/img/spell/${fullImageName}`
}

const WIKI_IMG_CDN = 'https://wiki.leagueoflegends.com/en-us/images/thumb'

// The official rune tree crest icons ddragon ships are only 32x32 and look blurry once
// upscaled. The League wiki hosts a sharper 85x85 flat-style version of the same crests.
export function runeTreeIconUrl(treeKey: string): string {
  return `${WIKI_IMG_CDN}/${treeKey}_icon.png/64px-${treeKey}_icon.png`
}
